[build]
  command = "npm run netlify"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/login"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard"
  status = 200

[[redirects]]
  from = "/actividades/*"
  to = "/actividades/:splat"
  status = 200